language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_install:
  - rm -f package-lock.json && npm install

script:
  - npm test -- -u
after_script:
  - npm run coveralls
